{
 "title": "BlockTime",
 "description": "Projeto de Monitoramento",
 "tags": [
  "AWS",
  "CloudWatch",
  "CloudTrail",
  "S3",
  "MySql",
  "Athena"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <a>\n        <img src=\"https://blog.flamingtext.com/blog/2024/11/10/flamingtext_com_1731209595_534616958.png\" width=\"1000\" height=\"300\">\n    </a>\n</div>\n"
   }
  },
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Leituras de disco (bytes)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Operações de gravação de disco (operações)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Total network traffic ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "InstanceId": "i-0738d02251988fe18" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "options": {
      "content": "<h4>Este painel monitora o desempenho e a utilização das instâncias EC2, fornecendo informações sobre o uso de CPU, tráfego de rede e pacotes de rede:</h4>\r\n\r\n<ul>\r\n  <li><strong>Utilização de CPU por Instância (máx.%):</strong> Percentual máximo de uso da CPU por instância, indicando a carga e o desempenho computacional.</li>\r\n  <li><strong>Tráfego Total de Rede (Saída + e Entrada -) [bytes/seg]:</strong> Total de dados trafegados por instância, incluindo saída e entrada, em bytes por segundo.</li>\r\n  <li><strong>Tráfego de Rede de Entrada por Instância [bytes/seg]:</strong> Dados recebidos por cada instância, monitorando a carga de entrada.</li>\r\n  <li><strong>Tráfego de Rede de Saída por Instância [bytes/seg]:</strong> Dados enviados por cada instância, monitorando a carga de saída.</li>\r\n  <li><strong>Pacotes de Rede de Entrada por Instância [IOPS]:</strong> Número de pacotes recebidos por cada instância, refletindo a frequência de entrada.</li>\r\n  <li><strong>Pacotes de Rede de Saída por Instância [IOPS]:</strong> Número de pacotes enviados por cada instância, refletindo a frequência de saída.</li>\r\n</ul>\r\n\r\n<div style=\"text-align: center;\">\r\n  <img src=\"https://icon.icepanel.io/AWS/svg/Compute/EC2.svg\" width=\"40\" height=\"40\" alt=\"EC2 logo\"/>\r\n</div>"
     }
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "billingdb",
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Espaço Livre",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Espaço de Armazenamento (em bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "BinLogDiskUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Quantidade de créditos de desempenho disponíveis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "BurstBalance",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": " Transferência de Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "EBSByteBalance%",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Write operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bancodb" },
     "metricName": "EBSIOBalance%",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 241 },
     "options": {
      "content": "<h4>Descrição das Métricas de Instâncias RDS</h4>\n\n<p>Este painel exibe métricas importantes para monitoramento de desempenho e capacidade das instâncias RDS, ajudando a identificar gargalos e otimizar o uso dos recursos de banco de dados:</p>\n\n<ul>\n  <li><strong>Utilização de CPU por Cluster [%]:</strong> Mostra a porcentagem de uso da CPU para cada cluster de banco de dados, refletindo a carga de processamento geral.</li>\n  <li><strong>Conexões ao Banco de Dados [contagem]:</strong> Exibe o número total de conexões de clientes ao banco de dados, monitorando a carga de conexões para cada cluster e instância.</li>\n  <li><strong>Utilização de CPU por Instância [%]:</strong> Mostra a porcentagem de uso da CPU para cada instância RDS, indicando o uso de processamento individual.</li>\n  <li><strong>Espaço de Armazenamento Disponível [GiB]:</strong> Mede o espaço de armazenamento ainda disponível no banco de dados, ajudando a prever e evitar escassez de armazenamento.</li>\n  <li><strong>Memória RAM Disponível [MB]:</strong> Exibe a quantidade de memória RAM livre, essencial para acompanhar a disponibilidade de memória e o desempenho do banco de dados.</li>\n  <li><strong>Taxa de Leitura [bytes/seg]:</strong> Mede o volume de dados lidos por segundo, refletindo a taxa de leitura de dados do disco para o banco de dados.</li>\n  <li><strong>Taxa de Escrita [bytes/seg]:</strong> Indica o volume de dados escritos por segundo, monitorando a taxa de gravação de dados no disco.</li>\n  <li><strong>Latência de Leitura [seg]:</strong> Tempo médio de espera para operações de leitura, indicando o desempenho e a resposta de leitura.</li>\n  <li><strong>Latência de Escrita [seg]:</strong> Tempo médio de espera para operações de escrita, indicando o desempenho e a resposta de gravação.</li>\n  <li><strong>Operações de Leitura [IOPS]:</strong> Número de operações de leitura por segundo, ajudando a monitorar a carga de leitura no banco de dados.</li>\n  <li><strong>Operações de Escrita [IOPS]:</strong> Número de operações de escrita por segundo, refletindo a carga de gravação no banco de dados.</li>\n</ul>\n\n<div style=\"text-align: center;\">\n  <img src=\"https://icon.icepanel.io/AWS/svg/Database/RDS.svg\" width=\"40\" height=\"40\" alt=\"RDS logo\"/>\n</div>\n"
     }
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  { "title": "CloudTrail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Atividades por Usuário",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT SUBSTRING_INDEX(userIdentity, ':user/', -1) AS Usuário, \r\n       eventName AS Evento, \r\n       COUNT(*) AS Quantidade, \r\n       DATE_FORMAT(eventTime, '%Y-%m-%d %H:%i:%s') AS Periodo\r\nFROM cloudtrail_logs\r\nWHERE eventTime BETWEEN NOW() - INTERVAL 7 DAY AND NOW() and userIdentity is not NULL\r\nGROUP BY Usuário, Evento, Periodo\r\nORDER BY Periodo DESC;\r\n"
    }
   ]
  },
  {
   "title": "Consumo DIario de Serviços",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CONVERT_TZ(eventTime, '+00:00', '+03:00') AS Data_hora,  -- Converte o horário para o fuso de Brasília (UTC+3)\r\n    eventSource AS Evento                                   -- Exibe o serviço que gerou o evento\r\nFROM\r\n    cloudtrail_logs\r\nWHERE\r\n    eventTime >= (                                           -- O evento mais antigo\r\n        SELECT MIN(eventTime) \r\n        FROM cloudtrail_logs\r\n    ) \r\n    AND eventTime <= (                                       -- O evento mais recente\r\n        SELECT MAX(eventTime) \r\n        FROM cloudtrail_logs\r\n    )\r\nORDER BY\r\n    Data_hora DESC;                                           -- Ordena os eventos pelo horário ajustado para Brasília\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Histórico de Alterações de Serviços",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT eventName AS Evento, \r\n       eventSource AS Serviços, \r\n       SUBSTRING_INDEX(userIdentity, ':user/', -1) AS Usuário, \r\n       DATE_FORMAT(eventTime, '%Y-%m-%d %H:%i:%s') as Data_Hora,\r\n       sourceIPAddress AS IP_Fonte\r\nFROM cloudtrail_logs\r\nwhere userIdentity is not null \r\nORDER BY eventTime DESC \r\nLIMIT 50;\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Chamadas de API por Serviço",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT eventSource AS Serviço, \r\n       COUNT(*) AS Chamadas_API, \r\n       DATE_FORMAT(eventTime, '%Y-%m-%d %H:%i:%s') AS Data_Hora\r\nFROM cloudtrail_logs\r\nGROUP BY Serviço, Data_Hora\r\nORDER BY Data_Hora DESC;\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Eventos com Falhas",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    eventName AS Nome_Evento,\r\n    COUNT(*) AS Total_Erros,\r\n    DATE_FORMAT(eventTime, '%Y-%m-%d %H:%i:%s') AS Periodo\r\nFROM cloudtrail_logs\r\nWHERE errorCode IS NOT NULL\r\n    AND eventTime BETWEEN NOW() - INTERVAL 7 DAY AND NOW()\r\nGROUP BY Nome_Evento, Periodo\r\nORDER BY Periodo DESC, Total_Erros DESC;\r\n"
    }
   ]
  },
  {
   "title": "Eventos por Tipo de Ação (API)",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT eventSource AS Serviço, \r\n       errorCode AS Tipo_Erro, \r\n       COUNT(*) AS Qtd_Erro, \r\n       DATE_FORMAT(eventTime, '%Y-%m-%d %H:%i:%s') AS Periodo\r\nFROM cloudtrail_logs\r\nWHERE errorCode IS NOT NULL \r\n  AND eventTime BETWEEN NOW() - INTERVAL 7 DAY AND NOW()\r\nGROUP BY Serviço, Tipo_Erro, Periodo\r\nORDER BY Periodo DESC;\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Acessos por IP",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT sourceIPAddress AS IP_Fonte, \r\n       COUNT(*) AS Chamadas, \r\n       DATE_FORMAT(eventTime, '%Y-%m-%d %H:%i:%s') AS Periodo\r\nFROM cloudtrail_logs\r\nWHERE eventTime BETWEEN NOW() - INTERVAL 7 DAY AND NOW()\r\nGROUP BY IP_Fonte, Periodo\r\nORDER BY Periodo DESC, Chamadas DESC;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "options": {
    "content": "<h4>Descrição das Métricas de Monitoramento do CloudTrail</h4>\n\n<p>Este painel fornece uma visão detalhada do uso e das atividades de API, ajudando a rastrear alterações em recursos e o consumo diário de serviços na AWS:</p>\n\n<ul>\n  <li><strong>Consumo Diário de Serviços:</strong> Exibe o uso diário de diferentes serviços da AWS, permitindo monitorar a variação de consumo e identificar picos de utilização.</li>\n  <li><strong>Visão Geral de Atividades de API:</strong> Apresenta um resumo das chamadas de API realizadas, fornecendo uma visão clara das interações com serviços e ajudando a rastrear ações.</li>\n  <li><strong>Histórico de Alterações de Recursos:</strong> Registra as alterações feitas nos recursos da AWS, permitindo acompanhar modificações e facilitar auditorias de conformidade.</li>\n</ul>\n\n<div style=\"text-align: center;\">\n  <img src=\"https://icon.icepanel.io/AWS/svg/Management-Governance/CloudTrail.svg\" width=\"40\" height=\"40\" alt=\"CloudTrail logo\"/>\n</div>\n"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  { "title": "CUR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Fatura Atual",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    line_item_usage_account_id AS Conta,                -- Conta da AWS\r\n    product_product_name AS Serviço,                    -- Serviço da AWS\r\n    COUNT(*) AS Total_Ultilizado,                       -- Número total de itens de custo\r\n    ROUND(SUM(line_item_blended_cost), 2) AS Custo_Por_Mês, -- Custo total do serviço no mês com 2 casas decimais\r\n    ROUND((\r\n        SELECT SUM(line_item_blended_cost)                 -- Soma de todos os custos no período\r\n        FROM cur AS total_cost\r\n        WHERE total_cost.line_item_usage_start_date >= '2024-12-01' \r\n          AND total_cost.line_item_usage_end_date <= '2024-12-31'\r\n    ), 2) AS Custo_Total_Do_Mês                         -- Custo total de todos os serviços no período\r\nFROM \r\n    cur                                                 -- Nome da tabela CUR\r\nWHERE \r\n    line_item_usage_start_date >= '2024-12-01'          -- Início do período (1º de dezembro de 2024)\r\n    AND line_item_usage_end_date <= '2024-12-31'        -- Fim do período (31 de dezembro de 2024)\r\nGROUP BY \r\n    line_item_usage_account_id, \r\n    product_product_name\r\nORDER BY \r\n    Custo_Por_Mês DESC;\r\n"
    }
   ]
  },
  {
   "title": "Fatura do mês anterior",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'Banco Relacional' AS Servico, \r\n    custo_banco_relacional AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Instâncias EC2' AS Servico, \r\n    custo_instancias_ec2 AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Impostos' AS Servico, \r\n    custo_impostos AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'EC2 Outros' AS Servico, \r\n    custo_ec2_outros AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'VPC' AS Servico, \r\n    custo_vpc AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Route 53' AS Servico, \r\n    custo_route53 AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'CloudWatch' AS Servico, \r\n    custo_cloudwatch AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'CloudTrail' AS Servico, \r\n    custo_cloudtrail AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'S3' AS Servico, \r\n    custo_s3 AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Orçamentos' AS Servico, \r\n    custo_orcamentos AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'ECR' AS Servico, \r\n    custo_ecr AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'EFS' AS Servico, \r\n    custo_efs AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Backup' AS Servico, \r\n    custo_backup AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Amplify' AS Servico, \r\n    custo_amplify AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Lambda' AS Servico, \r\n    custo_lambda AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'SNS' AS Servico, \r\n    custo_sns AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'Glue' AS Servico, \r\n    custo_glue AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01'\r\nUNION ALL\r\nSELECT \r\n    'KMS' AS Servico, \r\n    custo_kms AS ValorServico,\r\n    custo_total AS ValorTotal\r\nFROM custos_servicos \r\nWHERE servico = '2024-11-01';\r\n"
    }
   ]
  },
  {
   "title": "Serviços",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "dataset": "billingdb",
     "rawSql": "SELECT DISTINCT product_product_name\r\nFROM billingdb.cur\r\nWHERE product_product_name IS NOT NULL \r\n  AND product_product_name <> ''\r\nLIMIT 100;\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Resumo de Uso",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    product_product_name AS \"Serviço\",\r\n    'USD$' AS \"Moeda\",\r\n    SUM(FLOOR(line_item_usage_amount)) AS \"Vezes de Uso\",\r\n    CONCAT('$', FORMAT(SUM(pricing_public_on_demand_cost), 2)) AS \"Custo Total Sob Demanda\"\r\nFROM\r\n    billingdb.cur\r\nWHERE\r\n    product_product_name IS NOT NULL \r\n    AND product_product_name <> ''\r\nGROUP BY\r\n    product_product_name\r\nORDER BY\r\n    \"Serviço\";\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "AWS Lambda",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryMode": "Metrics",
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'AWS Lambda';\r\n",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CloudWatch",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'AmazonCloudWatch';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Amazon Simple Notification Service ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'Amazon Simple Notification Service';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "AWS Key Management Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'AWS Key Management Service';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Amazon Relational Database Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'Amazon Relational Database Service';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "AWS CloudTrail",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'AWS CloudTrail';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "S3",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'Amazon Simple Storage Service';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": " Amazon Virtual Private Cloud",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'Amazon Virtual Private Cloud';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "AWS Data Transfer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    identity_line_item_id AS \"ID da Linha de Item\",\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    line_item_blended_cost AS \"Custo Misturado\",\r\n    product_product_name AS \"Serviço\",\r\n    pricing_currency AS \"Moeda\",\r\n    pricing_public_on_demand_cost AS \"Custo Sob Demanda\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'AWS Data Transfer';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "title": "Amazon Elastic Compute Cloud",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    line_item_usage_type AS \"Tipo de Uso\",\r\n    line_item_usage_amount AS \"Quantidade de Uso\",\r\n    product_product_name AS \"Serviço\"\r\nFROM \r\n    billingdb.cur\r\nWHERE product_product_name = 'Amazon Elastic Compute Cloud';\r\n",
     "region": "default"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 157 },
   "options": {
    "content": "<h4>Descrição das Métricas de Monitoramento do Relatório de Custo e Uso (CUR)</h4>\r\n\r\n<p>Este painel fornece uma visão abrangente sobre o consumo e os custos dos serviços da AWS, permitindo monitorar e gerenciar gastos com base nas atividades diárias:</p>\r\n\r\n<ul>\r\n  <li><strong>Serviços:</strong> Apresenta um resumo dos custos por serviço, ajudando a identificar quais serviços estão gerando mais despesas.</li>\r\n  <li><strong>Fatura Atual:</strong> Exibe o valor atualizado da fatura até o momento, permitindo o acompanhamento do custo acumulado no período.</li>\r\n  <li><strong>AWS Lambda:</strong> Monitora o custo e o uso das funções Lambda, fornecendo insights sobre a eficiência das execuções de código sob demanda.</li>\r\n  <li><strong>Amazon Athena:</strong> Analisa o custo das consultas realizadas no Athena, facilitando a visualização dos gastos com análise de dados.</li>\r\n  <li><strong>Amazon Simple Storage Service (S3):</strong> Exibe o uso e os custos associados ao armazenamento e transferência de dados no S3.</li>\r\n  <li><strong>Amazon CloudWatch:</strong> Mostra os custos relacionados ao monitoramento de métricas, permitindo gerenciar o uso do CloudWatch.</li>\r\n  <li><strong>AWS Data Transfer:</strong> Apresenta o custo do tráfego de dados entre regiões e zonas, ajudando a controlar despesas de transferência.</li>\r\n  <li><strong>Amazon Virtual Private Cloud (VPC):</strong> Monitora os custos associados à infraestrutura de rede privada virtual na AWS.</li>\r\n  <li><strong>CloudWatch Events:</strong> Exibe o custo relacionado ao uso de eventos no CloudWatch para agendamento e automação de tarefas.</li>\r\n  <li><strong>AWS CloudTrail:</strong> Apresenta o custo associado ao registro e auditoria de atividades na conta.</li>\r\n  <li><strong>Amazon Simple Notification Service (SNS):</strong> Monitora os custos de notificações e mensagens enviadas por meio do SNS.</li>\r\n  <li><strong>Amazon Simple Queue Service (SQS):</strong> Exibe o custo relacionado ao uso de filas para o processamento assíncrono de mensagens.</li>\r\n  <li><strong>AWS Key Management Service (KMS):</strong> Monitora os custos associados à gestão e uso de chaves de criptografia no KMS.</li>\r\n  <li><strong>AWS Glue:</strong> Exibe os custos das operações de ETL e processamento de dados realizadas pelo Glue.</li>\r\n  <li><strong>Amazon Relational Database Service (RDS):</strong> Monitora o custo e uso das instâncias de banco de dados gerenciadas no RDS.</li>\r\n  <li><strong>Amazon Elastic Compute Cloud (EC2):</strong> Exibe o custo de uso das instâncias EC2, permitindo controlar o uso de recursos computacionais.</li>\r\n</ul>\r\n\r\n<div style=\"text-align: center;\">\r\n  <img src=\"https://icon.icepanel.io/AWS/svg/Cloud-Financial-Management/Cost-and-Usage-Report.svg\" width=\"40\" height=\"40\" alt=\"CUR logo\"/>\r\n</div>\r\n"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 173 },
   "options": {
    "content": "Integrantes :\n\n- Marcelo Mesquita\n- Kauã \n- Rafael\n- Bruno"
   }
  }
 ]
}